version: "3"
services:
  nginx:
    image: nginx:alpine
    container_name: nginx-server
    restart: unless-stopped
    depends_on:
      - game-web
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static-content:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - awesome
  game-web:
    build:
      context: ./packages/web
    env_file: .env
    depends_on:
      - game-api
    ports:
      - "5000:5000"
    volumes:
      - static-content:/app/dist/
    restart: always
    networks:
      - awesome
  game-api:
    build:
      context: ./packages/api
    depends_on:
      - postgres
    ports:
      - "3001:3001"
    restart: always
    env_file: .env
    networks:
      - awesome
  postgres:
    container_name: postgres
    image: postgres:12
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    env_file: .env
    networks:
      - awesome

volumes:
  postgres-data:
  static-content:

networks:
  awesome:
    driver: bridge
